dist: xenial
language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - TESTS=true
  matrix:
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.07 EXTRA_DEPS="ocamlformat.0.9" PRE_INSTALL_HOOK="make format"
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:leonidas/libmaxminddb'
