name: Check Licenses
on: [pull_request]
jobs:
  check-licenses:
    runs-on: [self-hosted]
    permissions:
      pull-requests: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb # v4
      - uses: BendingSpoons/github-actions/check-licenses@61d566cd7b62810c302495c8976b18f3754343e2
        with:
          license-config-github-token: ${{ secrets.LICENSE_CONFIG_GITHUB_TOKEN }}
          scope: external
